version: '3.9'
services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app-frontend
    working_dir: /app-frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
  backend:
    build: ./backend
    volumes:
      - ./backend:/app-backend
    working_dir: /app-backend
    ports:
      - 3001:3001
    depends_on:
      db:
        condition: service_healthy
    environment:
      - APP_PORT=3001
      - DB_USER=root
      - DB_PASS=root
      - DB_HOST=db
      - DB_PORT=3306
    command: dev
  db:
    image: mysql:8.0.21
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    restart: 'always'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5